// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvC_S73vNLAT3iTLSnENTtq1HRz_hUEe8',
    appId: '1:1017812339061:web:47d56c53c0c6475e5ceb3c',
    messagingSenderId: '1017812339061',
    projectId: 'ditonton-7a41b',
    authDomain: 'ditonton-7a41b.firebaseapp.com',
    storageBucket: 'ditonton-7a41b.appspot.com',
    measurementId: 'G-GFYG66TWNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3_pieqWP-s4LxpZzPs5I3tKNzI2whaDk',
    appId: '1:1017812339061:android:952a4e7bbe2291e85ceb3c',
    messagingSenderId: '1017812339061',
    projectId: 'ditonton-7a41b',
    storageBucket: 'ditonton-7a41b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAICpQ9XNf6ZTTJcXDUzg2COnGgNnRs_uE',
    appId: '1:1017812339061:ios:0c7f45b61774644f5ceb3c',
    messagingSenderId: '1017812339061',
    projectId: 'ditonton-7a41b',
    storageBucket: 'ditonton-7a41b.appspot.com',
    iosClientId: '1017812339061-dvg7kevfg3pk4hnjfufcp676aprb8g96.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
